version: '3'

services:
  node-app:
    build: .
    image: node-app
    env_file: .env # Load environment variables from the .env file
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
